### ISSUE TITLE
Invite Tracking

### ISSUE THREAD

**Issue by kringeth000** [GreaterGamersLounge/bot_man#33]
- Relies on logging ( #6 )
- Track server joins against server invite links their use count
- Would be used to track who is inviting others
- Can be used as a metric down the line
- Probably would consist of a table in database; invite code, date created, created by, uses, timeExpired
- In conjunction with logging user joins, data can be used to track who invited who

**Comment by dracco1993** [comment]
Table information:
`invite`:
- `id`
- `server_uid`
- `inviter_uid`
- `code`
- `uses`
- `expires` (optional)
- `created_at`
- `updated_at`

`invite_user`:
- `invite_id`
- `joiner_uid`
- `created_at`
- `updated_at`

**Comment by kringeth000** [comment]
> `invite`:
> 
> * `id`
> * `server_uid`
> * `inviter_uid`
> * `code`
> * `uses`
> * `expires` (optional)
> * `created_at`
> * `updated_at`

Would it be worthwhile to have a column indicating whether or not the invite is still active? Additionally could be worth having columns for "# of uses" and "out of __ uses" (not sure on what a good name would be for them) as you can limit number of uses of an invite too.

**Comment by dracco1993** [comment]
TODO:
- [ ] Log creation of new invites
- [ ] Log changes to invites (can you even do this?)
- [ ] Log usage when someone joins the server
- [ ] Log all invites when bot is added to a server
- [ ] Log all invites on deploy to `prod` (probably through a script in a migration)
